### ISSUE TITLE
[Bug] [React] Object prototype may only be an Object or null

### ISSUE THREAD

**Issue by FirelightFlagboy** [syncfusion/ej2-javascript-ui-controls#38]
# Behavior
when building the app for production (`npm run prod` or `npm run build`), 
I got the error below :
```
Uncaught (in promise) TypeError: Object prototype may only be an Object or null: undefined
    at setPrototypeOf (<anonymous>)
```
But when I build for the dev server (`npm start`) no error everything work fine
# Version
the detail of verion are in the gist below (see [package.json](https://gist.github.com/FirelightFlagboy/2effce8b312432b46c312af0baec4683#file-package-json)), but i give a quick view
```
    "react": "^16.7.0",
    "react-dom": "^16.7.0",
    "@syncfusion/ej2-react-diagrams": "^16.4.48",
```
# How to reproduce
I create a gist to this [link](https://gist.github.com/FirelightFlagboy/2effce8b312432b46c312af0baec4683)
simply copy the file and do `npm i && npm run prod` to install dependencies and run the prod server

**Comment by FirelightFlagboy** [comment]
the error vanish when I do,
- remove the line `setNodeTemplate` in `<DiagramComponent />`
- remove `ImageElement, StackPanel, Node, TextElement` from the import

**Comment by FirelightFlagboy** [comment]
anyone ?

**Comment by RamyaThiru** [comment]
Hi,

We have logged a defect report for reported issue. This fix will be available in our next patch release on February 12th 2019.

Regards,
Ramya T

**Comment by FirelightFlagboy** [comment]
Hi,

i have tested to update `@syncfusion/ej2-react-diagrams` to version `^16.4.52`.
i still got the error

**Comment by FirelightFlagboy** [comment]
i update the [gist](https://gist.github.com/FirelightFlagboy/2effce8b312432b46c312af0baec4683), if you want to check

**Comment by FirelightFlagboy** [comment]
hi, 
i have update the [gist](https://gist.github.com/FirelightFlagboy/2effce8b312432b46c312af0baec4683),
to test the version `^16.4.53`. 

I still got the issue

**Comment by RamyaThiru** [comment]
Hi,
Sorry for the inconvenience caused.
Please do the below changes  in package.json file of diagram. Location of json file in your application: node_modules\@syncfusion\ej2-diagrams\package.json

**Code example Changes:**
"module": "./dist/es6/ej2-diagrams.es5.js",

![packagejson](https://user-images.githubusercontent.com/5535468/52950659-d6ed3100-33a5-11e9-9959-cb554cf79e52.png)

The fix will be available in our patch release on February 20th, 2019.
Regards,
Ramya T

**Comment by enjector** [comment]
Hi, 

This problem now exists in version 17.1.47. I was able to apply the same fix and it worked.

Can this is be rolled up in the latest version please?

Thanks

Ajay Soni
Enjector Software Ltd.

**Comment by RamyaThiru** [comment]
Hi Ajay,

Thanks for your patience.

We have fixed and included the fix for reported issue. This fix will be available in our next patch release on May 22nd, 2019.

Regards,
Ramya T

**Comment by RamyaThiru** [comment]
Hi Ajay,

We are glad to announce that our patch release (v17.1.48) is rolled out successfully and In that release, we have added the fix for the reported issue.

Regards, 
Ramya T

**Comment by shosho613** [comment]
This bug still reconstructs on version 17.2.51, is there any version that is stable considering this bug?
Thanks.

**Comment by sinires** [comment]
@shosho613 Try changing the import to @syncfusion/ej2-react-diagrams/dist/es6/ej2-react-diagrams.es2015. It worked for me in version 17.2.51

**Comment by enjector** [comment]
The bug still hasn't been fixed in 17.4.41. I am currently doing the manual workaround.

Any chance to get this simple change in please? Let me know if you would like a pull request.

**Comment by Sridhar-Narasimhan** [comment]
Hi ,

The reported issue has been fixed at our end and the fix for the issue has been included in our Essential Studio Volume 1, 2020 release (v18-1-0-42) and is available for download under the following link.
 
https://www.syncfusion.com/forums/152921/essential-studio-2020-volume-1-release-v18-1-0-42-is-available-for-download
 
We have attached a sample for your reference. Please find the sample in below link
 
Sample: https://www.syncfusion.com/downloads/support/directtrac/general/ze/Sample-197085378
